[tool.poetry]
name = "pythonprojectk1"
version = "0.1.0"
description = ""
authors = ["svetlana-kuprina <kupsveta@rambler.ru>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.13"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
